// <auto-generated />
namespace S2022A6MHN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateartistalbum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateartistalbum));
        
        string IMigrationMetadata.Id
        {
            get { return "202208071923200_update-artist-album"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
